Init
Teaching-projects/SZE-MOSZE-2020-Elon-Musk-t-sai--CLOSED pull request #2
Opened 2020-09-17 09:02 UTC by mszrs27

2020-09-18 08:44 UTC, hegyhati requested changes

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +using namespace std;
ezt legfeljebb a main-ben. Logika osztalyokban a using-ot keruljuk.

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    uint_t getDamage(){
const ahova lehet.

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    void receivedDamage(uint_t dmg){
ez tul altalanos, nem akarjuk hogy akarki akarmennyivel lecsokkenthesse az eletunket. Annyit akarunk csak megengedni, hogy egy masik unit megcsaphasson minket (a sebzesevel).

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    void receivedDamage(uint_t dmg){
illetve const?

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +        }else if(dmg>=health)
mi lenne az else?

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +        cout << name << " Received damage: " << dmg << " Health remaining: " << health <<endl;
logika osztalyban ne legyen semmilyen kiiratas.

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +            cout << name << " lost all Healthpoint." << endl;
u.a.

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    string name;
const?

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +class game{
1 file legyen 1 class

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    player2dmg = atoi(argv[6]);
ez akar feleennyi sorban is menne, sot, akar az alabbi sorokba is be lehetne tenni.

2020-09-18 08:44 UTC, hegyhati commented on rpg.cpp
> +    game g=game(p1,p2);
kicsit szebb ha nem =-vel van.
Illetve apro megjegyzes, de az atlathatosagot noveli, ha mondjuk pl a class-ok nagy betuvel kezdodnek. ITt nem latszodik annyira, hogy a game egy osztaly, a player1 meg egy objektum/valtozo.

2020-09-24 18:21 UTC, mszrs27 commented on rpg.cpp
> +        }else if(dmg>=health)
az else ágban kezeljük le, hogy az unsigned int nem mehet negatívba.

2020-09-24 21:20 UTC, mszrs27 commented
@hegyhati készen vannak a kért javítások

2020-09-24 22:13 UTC, hegyhati commented on rpg.cpp
> +        }else if(dmg>=health)
En csak else if-et latok. Else agat nem. A kerdes az volt, hogyha ez a ket feltetel van, akkor mi lenne az, amivel egy (nem letezo) else agban bemenne. Es ha semmi, akkor ez miert else if, es miert nem egy sima else?

2020-09-25 13:53 UTC, hegyhati requested changes
A constokat nem ertitek. Nem az a lenyeg, hogy egy konstans int-et adjunk vissza. Ha meg ma fixaljatok, es lesz idom ranezni, akkor beviszem.

2020-09-25 21:27 UTC, mszrs27 commented
@hegyhati pusholva

2020-09-26 14:03 UTC, hegyhati commented
Ez a kod most le sem fordulna, nem egyeznek meg a szignaturak. Sracok, ennyi, leveszuk a kezunket errol a reporol.

2020-09-26 14:03 UTC, closed without merging